"""fix

Revision ID: b2b1f533daa3
Revises: cfa5ffee0d60
Create Date: 2025-01-21 13:19:26.257959

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b2b1f533daa3'
down_revision = 'cfa5ffee0d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
